package com.pjxy.common.model;

public class Block {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column block.ID
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column block.PARENT
	 * @mbggenerated
	 */
	private Integer parent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column block.NAME
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column block.BANNER
	 * @mbggenerated
	 */
	private String banner;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column block.POST_COUNT
	 * @mbggenerated
	 */
	private Integer postCount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column block.ID
	 * @return  the value of block.ID
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column block.ID
	 * @param id  the value for block.ID
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column block.PARENT
	 * @return  the value of block.PARENT
	 * @mbggenerated
	 */
	public Integer getParent() {
		return parent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column block.PARENT
	 * @param parent  the value for block.PARENT
	 * @mbggenerated
	 */
	public void setParent(Integer parent) {
		this.parent = parent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column block.NAME
	 * @return  the value of block.NAME
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column block.NAME
	 * @param name  the value for block.NAME
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column block.BANNER
	 * @return  the value of block.BANNER
	 * @mbggenerated
	 */
	public String getBanner() {
		return banner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column block.BANNER
	 * @param banner  the value for block.BANNER
	 * @mbggenerated
	 */
	public void setBanner(String banner) {
		this.banner = banner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column block.POST_COUNT
	 * @return  the value of block.POST_COUNT
	 * @mbggenerated
	 */
	public Integer getPostCount() {
		return postCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column block.POST_COUNT
	 * @param postCount  the value for block.POST_COUNT
	 * @mbggenerated
	 */
	public void setPostCount(Integer postCount) {
		this.postCount = postCount;
	}
}