package com.pjxy.common.model;

public class Bulletin {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bulletin.ID
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bulletin.POST_ID
	 * @mbggenerated
	 */
	private Integer postId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bulletin.BLOCK_ID
	 * @mbggenerated
	 */
	private Integer blockId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bulletin.SHOW_NAME
	 * @mbggenerated
	 */
	private String showName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bulletin.ID
	 * @return  the value of bulletin.ID
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bulletin.ID
	 * @param id  the value for bulletin.ID
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bulletin.POST_ID
	 * @return  the value of bulletin.POST_ID
	 * @mbggenerated
	 */
	public Integer getPostId() {
		return postId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bulletin.POST_ID
	 * @param postId  the value for bulletin.POST_ID
	 * @mbggenerated
	 */
	public void setPostId(Integer postId) {
		this.postId = postId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bulletin.BLOCK_ID
	 * @return  the value of bulletin.BLOCK_ID
	 * @mbggenerated
	 */
	public Integer getBlockId() {
		return blockId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bulletin.BLOCK_ID
	 * @param blockId  the value for bulletin.BLOCK_ID
	 * @mbggenerated
	 */
	public void setBlockId(Integer blockId) {
		this.blockId = blockId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bulletin.SHOW_NAME
	 * @return  the value of bulletin.SHOW_NAME
	 * @mbggenerated
	 */
	public String getShowName() {
		return showName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bulletin.SHOW_NAME
	 * @param showName  the value for bulletin.SHOW_NAME
	 * @mbggenerated
	 */
	public void setShowName(String showName) {
		this.showName = showName;
	}
}