package com.pjxy.common.model;

import java.util.Date;

public class Post {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.ID
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.USER_ID
	 * @mbggenerated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.BLOCK_ID
	 * @mbggenerated
	 */
	private Integer blockId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.TITLE
	 * @mbggenerated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.VIEW_COUNT
	 * @mbggenerated
	 */
	private Integer viewCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.GOOD_COUNT
	 * @mbggenerated
	 */
	private Integer goodCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.BAD_COUNT
	 * @mbggenerated
	 */
	private Integer badCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.WELL
	 * @mbggenerated
	 */
	private Boolean well;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.BEST
	 * @mbggenerated
	 */
	private Boolean best;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.END
	 * @mbggenerated
	 */
	private Boolean end;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.LOCK
	 * @mbggenerated
	 */
	private Boolean lock;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.MARK
	 * @mbggenerated
	 */
	private Integer mark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.DELETED
	 * @mbggenerated
	 */
	private Boolean deleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.TOP_TYPE
	 * @mbggenerated
	 */
	private Short topType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.CREATE_TIME
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.REPLY_TIME
	 * @mbggenerated
	 */
	private Date replyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.REPLY_COUNT
	 * @mbggenerated
	 */
	private Integer replyCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.REPLY_HAS_TOP
	 * @mbggenerated
	 */
	private Integer replyHasTop;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.FAV_COUNT
	 * @mbggenerated
	 */
	private Integer favCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.AUTHOR_NAME
	 * @mbggenerated
	 */
	private String authorName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.HAS_ATTACHMENT
	 * @mbggenerated
	 */
	private Boolean hasAttachment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.HAS_VOTE
	 * @mbggenerated
	 */
	private Boolean hasVote;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column post.CONTENT
	 * @mbggenerated
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.ID
	 * @return  the value of post.ID
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.ID
	 * @param id  the value for post.ID
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.USER_ID
	 * @return  the value of post.USER_ID
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.USER_ID
	 * @param userId  the value for post.USER_ID
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.BLOCK_ID
	 * @return  the value of post.BLOCK_ID
	 * @mbggenerated
	 */
	public Integer getBlockId() {
		return blockId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.BLOCK_ID
	 * @param blockId  the value for post.BLOCK_ID
	 * @mbggenerated
	 */
	public void setBlockId(Integer blockId) {
		this.blockId = blockId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.TITLE
	 * @return  the value of post.TITLE
	 * @mbggenerated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.TITLE
	 * @param title  the value for post.TITLE
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.VIEW_COUNT
	 * @return  the value of post.VIEW_COUNT
	 * @mbggenerated
	 */
	public Integer getViewCount() {
		return viewCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.VIEW_COUNT
	 * @param viewCount  the value for post.VIEW_COUNT
	 * @mbggenerated
	 */
	public void setViewCount(Integer viewCount) {
		this.viewCount = viewCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.GOOD_COUNT
	 * @return  the value of post.GOOD_COUNT
	 * @mbggenerated
	 */
	public Integer getGoodCount() {
		return goodCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.GOOD_COUNT
	 * @param goodCount  the value for post.GOOD_COUNT
	 * @mbggenerated
	 */
	public void setGoodCount(Integer goodCount) {
		this.goodCount = goodCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.BAD_COUNT
	 * @return  the value of post.BAD_COUNT
	 * @mbggenerated
	 */
	public Integer getBadCount() {
		return badCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.BAD_COUNT
	 * @param badCount  the value for post.BAD_COUNT
	 * @mbggenerated
	 */
	public void setBadCount(Integer badCount) {
		this.badCount = badCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.WELL
	 * @return  the value of post.WELL
	 * @mbggenerated
	 */
	public Boolean getWell() {
		return well;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.WELL
	 * @param well  the value for post.WELL
	 * @mbggenerated
	 */
	public void setWell(Boolean well) {
		this.well = well;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.BEST
	 * @return  the value of post.BEST
	 * @mbggenerated
	 */
	public Boolean getBest() {
		return best;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.BEST
	 * @param best  the value for post.BEST
	 * @mbggenerated
	 */
	public void setBest(Boolean best) {
		this.best = best;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.END
	 * @return  the value of post.END
	 * @mbggenerated
	 */
	public Boolean getEnd() {
		return end;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.END
	 * @param end  the value for post.END
	 * @mbggenerated
	 */
	public void setEnd(Boolean end) {
		this.end = end;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.LOCK
	 * @return  the value of post.LOCK
	 * @mbggenerated
	 */
	public Boolean getLock() {
		return lock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.LOCK
	 * @param lock  the value for post.LOCK
	 * @mbggenerated
	 */
	public void setLock(Boolean lock) {
		this.lock = lock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.MARK
	 * @return  the value of post.MARK
	 * @mbggenerated
	 */
	public Integer getMark() {
		return mark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.MARK
	 * @param mark  the value for post.MARK
	 * @mbggenerated
	 */
	public void setMark(Integer mark) {
		this.mark = mark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.DELETED
	 * @return  the value of post.DELETED
	 * @mbggenerated
	 */
	public Boolean getDeleted() {
		return deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.DELETED
	 * @param deleted  the value for post.DELETED
	 * @mbggenerated
	 */
	public void setDeleted(Boolean deleted) {
		this.deleted = deleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.TOP_TYPE
	 * @return  the value of post.TOP_TYPE
	 * @mbggenerated
	 */
	public Short getTopType() {
		return topType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.TOP_TYPE
	 * @param topType  the value for post.TOP_TYPE
	 * @mbggenerated
	 */
	public void setTopType(Short topType) {
		this.topType = topType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.CREATE_TIME
	 * @return  the value of post.CREATE_TIME
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.CREATE_TIME
	 * @param createTime  the value for post.CREATE_TIME
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.REPLY_TIME
	 * @return  the value of post.REPLY_TIME
	 * @mbggenerated
	 */
	public Date getReplyTime() {
		return replyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.REPLY_TIME
	 * @param replyTime  the value for post.REPLY_TIME
	 * @mbggenerated
	 */
	public void setReplyTime(Date replyTime) {
		this.replyTime = replyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.REPLY_COUNT
	 * @return  the value of post.REPLY_COUNT
	 * @mbggenerated
	 */
	public Integer getReplyCount() {
		return replyCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.REPLY_COUNT
	 * @param replyCount  the value for post.REPLY_COUNT
	 * @mbggenerated
	 */
	public void setReplyCount(Integer replyCount) {
		this.replyCount = replyCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.REPLY_HAS_TOP
	 * @return  the value of post.REPLY_HAS_TOP
	 * @mbggenerated
	 */
	public Integer getReplyHasTop() {
		return replyHasTop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.REPLY_HAS_TOP
	 * @param replyHasTop  the value for post.REPLY_HAS_TOP
	 * @mbggenerated
	 */
	public void setReplyHasTop(Integer replyHasTop) {
		this.replyHasTop = replyHasTop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.FAV_COUNT
	 * @return  the value of post.FAV_COUNT
	 * @mbggenerated
	 */
	public Integer getFavCount() {
		return favCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.FAV_COUNT
	 * @param favCount  the value for post.FAV_COUNT
	 * @mbggenerated
	 */
	public void setFavCount(Integer favCount) {
		this.favCount = favCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.AUTHOR_NAME
	 * @return  the value of post.AUTHOR_NAME
	 * @mbggenerated
	 */
	public String getAuthorName() {
		return authorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.AUTHOR_NAME
	 * @param authorName  the value for post.AUTHOR_NAME
	 * @mbggenerated
	 */
	public void setAuthorName(String authorName) {
		this.authorName = authorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.HAS_ATTACHMENT
	 * @return  the value of post.HAS_ATTACHMENT
	 * @mbggenerated
	 */
	public Boolean getHasAttachment() {
		return hasAttachment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.HAS_ATTACHMENT
	 * @param hasAttachment  the value for post.HAS_ATTACHMENT
	 * @mbggenerated
	 */
	public void setHasAttachment(Boolean hasAttachment) {
		this.hasAttachment = hasAttachment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.HAS_VOTE
	 * @return  the value of post.HAS_VOTE
	 * @mbggenerated
	 */
	public Boolean getHasVote() {
		return hasVote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.HAS_VOTE
	 * @param hasVote  the value for post.HAS_VOTE
	 * @mbggenerated
	 */
	public void setHasVote(Boolean hasVote) {
		this.hasVote = hasVote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column post.CONTENT
	 * @return  the value of post.CONTENT
	 * @mbggenerated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column post.CONTENT
	 * @param content  the value for post.CONTENT
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content;
	}
}