package com.pjxy.common.model;

import java.util.Date;

public class Regist {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regist.ID
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regist.MOBILE
	 * @mbggenerated
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column regist.CREATE_TIME
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regist.ID
	 * @return  the value of regist.ID
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regist.ID
	 * @param id  the value for regist.ID
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regist.MOBILE
	 * @return  the value of regist.MOBILE
	 * @mbggenerated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regist.MOBILE
	 * @param mobile  the value for regist.MOBILE
	 * @mbggenerated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column regist.CREATE_TIME
	 * @return  the value of regist.CREATE_TIME
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column regist.CREATE_TIME
	 * @param createTime  the value for regist.CREATE_TIME
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}