package com.pjxy.common.model;

import java.util.Date;

public class Reply {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.ID
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.USER_ID
	 * @mbggenerated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.POST_ID
	 * @mbggenerated
	 */
	private Integer postId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.CREATE_TIME
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.TOP
	 * @mbggenerated
	 */
	private Boolean top;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.MARK
	 * @mbggenerated
	 */
	private Integer mark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.USER_NAME
	 * @mbggenerated
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.CONTENT
	 * @mbggenerated
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.ID
	 * @return  the value of reply.ID
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.ID
	 * @param id  the value for reply.ID
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.USER_ID
	 * @return  the value of reply.USER_ID
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.USER_ID
	 * @param userId  the value for reply.USER_ID
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.POST_ID
	 * @return  the value of reply.POST_ID
	 * @mbggenerated
	 */
	public Integer getPostId() {
		return postId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.POST_ID
	 * @param postId  the value for reply.POST_ID
	 * @mbggenerated
	 */
	public void setPostId(Integer postId) {
		this.postId = postId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.CREATE_TIME
	 * @return  the value of reply.CREATE_TIME
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.CREATE_TIME
	 * @param createTime  the value for reply.CREATE_TIME
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.TOP
	 * @return  the value of reply.TOP
	 * @mbggenerated
	 */
	public Boolean getTop() {
		return top;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.TOP
	 * @param top  the value for reply.TOP
	 * @mbggenerated
	 */
	public void setTop(Boolean top) {
		this.top = top;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.MARK
	 * @return  the value of reply.MARK
	 * @mbggenerated
	 */
	public Integer getMark() {
		return mark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.MARK
	 * @param mark  the value for reply.MARK
	 * @mbggenerated
	 */
	public void setMark(Integer mark) {
		this.mark = mark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.USER_NAME
	 * @return  the value of reply.USER_NAME
	 * @mbggenerated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.USER_NAME
	 * @param userName  the value for reply.USER_NAME
	 * @mbggenerated
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.CONTENT
	 * @return  the value of reply.CONTENT
	 * @mbggenerated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.CONTENT
	 * @param content  the value for reply.CONTENT
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content;
	}
}