package com.pjxy.common.model;

import java.util.Date;

public class Admin {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.ID
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.USER_ID
	 * @mbggenerated
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.BLOCK_ID
	 * @mbggenerated
	 */
	private Integer blockId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.MANAGE_TYPE
	 * @mbggenerated
	 */
	private Byte manageType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.CREATE_TIME
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin.USER_NAME
	 * @mbggenerated
	 */
	private String userName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.ID
	 * @return  the value of admin.ID
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.ID
	 * @param id  the value for admin.ID
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.USER_ID
	 * @return  the value of admin.USER_ID
	 * @mbggenerated
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.USER_ID
	 * @param userId  the value for admin.USER_ID
	 * @mbggenerated
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.BLOCK_ID
	 * @return  the value of admin.BLOCK_ID
	 * @mbggenerated
	 */
	public Integer getBlockId() {
		return blockId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.BLOCK_ID
	 * @param blockId  the value for admin.BLOCK_ID
	 * @mbggenerated
	 */
	public void setBlockId(Integer blockId) {
		this.blockId = blockId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.MANAGE_TYPE
	 * @return  the value of admin.MANAGE_TYPE
	 * @mbggenerated
	 */
	public Byte getManageType() {
		return manageType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.MANAGE_TYPE
	 * @param manageType  the value for admin.MANAGE_TYPE
	 * @mbggenerated
	 */
	public void setManageType(Byte manageType) {
		this.manageType = manageType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.CREATE_TIME
	 * @return  the value of admin.CREATE_TIME
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.CREATE_TIME
	 * @param createTime  the value for admin.CREATE_TIME
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin.USER_NAME
	 * @return  the value of admin.USER_NAME
	 * @mbggenerated
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin.USER_NAME
	 * @param userName  the value for admin.USER_NAME
	 * @mbggenerated
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}
}