package com.pjxy.common.model;

import java.util.ArrayList;
import java.util.List;

public class BulletinExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bulletin
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bulletin
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bulletin
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bulletin
	 * @mbggenerated
	 */
	protected int limitStart = -1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table bulletin
	 * @mbggenerated
	 */
	protected int limitEnd = -1;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bulletin
	 * @mbggenerated
	 */
	public BulletinExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bulletin
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bulletin
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bulletin
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bulletin
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bulletin
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bulletin
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bulletin
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bulletin
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bulletin
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bulletin
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bulletin
	 * @mbggenerated
	 */
	public void setLimitStart(int limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bulletin
	 * @mbggenerated
	 */
	public int getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bulletin
	 * @mbggenerated
	 */
	public void setLimitEnd(int limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table bulletin
	 * @mbggenerated
	 */
	public int getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bulletin
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPostIdIsNull() {
			addCriterion("POST_ID is null");
			return (Criteria) this;
		}

		public Criteria andPostIdIsNotNull() {
			addCriterion("POST_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPostIdEqualTo(Integer value) {
			addCriterion("POST_ID =", value, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdNotEqualTo(Integer value) {
			addCriterion("POST_ID <>", value, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdGreaterThan(Integer value) {
			addCriterion("POST_ID >", value, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("POST_ID >=", value, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdLessThan(Integer value) {
			addCriterion("POST_ID <", value, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdLessThanOrEqualTo(Integer value) {
			addCriterion("POST_ID <=", value, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdIn(List<Integer> values) {
			addCriterion("POST_ID in", values, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdNotIn(List<Integer> values) {
			addCriterion("POST_ID not in", values, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdBetween(Integer value1, Integer value2) {
			addCriterion("POST_ID between", value1, value2, "postId");
			return (Criteria) this;
		}

		public Criteria andPostIdNotBetween(Integer value1, Integer value2) {
			addCriterion("POST_ID not between", value1, value2, "postId");
			return (Criteria) this;
		}

		public Criteria andBlockIdIsNull() {
			addCriterion("BLOCK_ID is null");
			return (Criteria) this;
		}

		public Criteria andBlockIdIsNotNull() {
			addCriterion("BLOCK_ID is not null");
			return (Criteria) this;
		}

		public Criteria andBlockIdEqualTo(Integer value) {
			addCriterion("BLOCK_ID =", value, "blockId");
			return (Criteria) this;
		}

		public Criteria andBlockIdNotEqualTo(Integer value) {
			addCriterion("BLOCK_ID <>", value, "blockId");
			return (Criteria) this;
		}

		public Criteria andBlockIdGreaterThan(Integer value) {
			addCriterion("BLOCK_ID >", value, "blockId");
			return (Criteria) this;
		}

		public Criteria andBlockIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("BLOCK_ID >=", value, "blockId");
			return (Criteria) this;
		}

		public Criteria andBlockIdLessThan(Integer value) {
			addCriterion("BLOCK_ID <", value, "blockId");
			return (Criteria) this;
		}

		public Criteria andBlockIdLessThanOrEqualTo(Integer value) {
			addCriterion("BLOCK_ID <=", value, "blockId");
			return (Criteria) this;
		}

		public Criteria andBlockIdIn(List<Integer> values) {
			addCriterion("BLOCK_ID in", values, "blockId");
			return (Criteria) this;
		}

		public Criteria andBlockIdNotIn(List<Integer> values) {
			addCriterion("BLOCK_ID not in", values, "blockId");
			return (Criteria) this;
		}

		public Criteria andBlockIdBetween(Integer value1, Integer value2) {
			addCriterion("BLOCK_ID between", value1, value2, "blockId");
			return (Criteria) this;
		}

		public Criteria andBlockIdNotBetween(Integer value1, Integer value2) {
			addCriterion("BLOCK_ID not between", value1, value2, "blockId");
			return (Criteria) this;
		}

		public Criteria andShowNameIsNull() {
			addCriterion("SHOW_NAME is null");
			return (Criteria) this;
		}

		public Criteria andShowNameIsNotNull() {
			addCriterion("SHOW_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andShowNameEqualTo(String value) {
			addCriterion("SHOW_NAME =", value, "showName");
			return (Criteria) this;
		}

		public Criteria andShowNameNotEqualTo(String value) {
			addCriterion("SHOW_NAME <>", value, "showName");
			return (Criteria) this;
		}

		public Criteria andShowNameGreaterThan(String value) {
			addCriterion("SHOW_NAME >", value, "showName");
			return (Criteria) this;
		}

		public Criteria andShowNameGreaterThanOrEqualTo(String value) {
			addCriterion("SHOW_NAME >=", value, "showName");
			return (Criteria) this;
		}

		public Criteria andShowNameLessThan(String value) {
			addCriterion("SHOW_NAME <", value, "showName");
			return (Criteria) this;
		}

		public Criteria andShowNameLessThanOrEqualTo(String value) {
			addCriterion("SHOW_NAME <=", value, "showName");
			return (Criteria) this;
		}

		public Criteria andShowNameLike(String value) {
			addCriterion("SHOW_NAME like", value, "showName");
			return (Criteria) this;
		}

		public Criteria andShowNameNotLike(String value) {
			addCriterion("SHOW_NAME not like", value, "showName");
			return (Criteria) this;
		}

		public Criteria andShowNameIn(List<String> values) {
			addCriterion("SHOW_NAME in", values, "showName");
			return (Criteria) this;
		}

		public Criteria andShowNameNotIn(List<String> values) {
			addCriterion("SHOW_NAME not in", values, "showName");
			return (Criteria) this;
		}

		public Criteria andShowNameBetween(String value1, String value2) {
			addCriterion("SHOW_NAME between", value1, value2, "showName");
			return (Criteria) this;
		}

		public Criteria andShowNameNotBetween(String value1, String value2) {
			addCriterion("SHOW_NAME not between", value1, value2, "showName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table bulletin
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bulletin
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}