package com.pjxy.common.model;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.ID
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.NAME
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.PASSWORD
	 * @mbggenerated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.SESSIONID
	 * @mbggenerated
	 */
	private String sessionid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.MOBILE
	 * @mbggenerated
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.ONLINE
	 * @mbggenerated
	 */
	private Boolean online;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.EMAIL
	 * @mbggenerated
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.MARK
	 * @mbggenerated
	 */
	private Integer mark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.MONEY
	 * @mbggenerated
	 */
	private Integer money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.LOGIN_TIME
	 * @mbggenerated
	 */
	private Date loginTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.REG_TIME
	 * @mbggenerated
	 */
	private Date regTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.ID
	 * @return  the value of user.ID
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.ID
	 * @param id  the value for user.ID
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.NAME
	 * @return  the value of user.NAME
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.NAME
	 * @param name  the value for user.NAME
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.PASSWORD
	 * @return  the value of user.PASSWORD
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.PASSWORD
	 * @param password  the value for user.PASSWORD
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.SESSIONID
	 * @return  the value of user.SESSIONID
	 * @mbggenerated
	 */
	public String getSessionid() {
		return sessionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.SESSIONID
	 * @param sessionid  the value for user.SESSIONID
	 * @mbggenerated
	 */
	public void setSessionid(String sessionid) {
		this.sessionid = sessionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.MOBILE
	 * @return  the value of user.MOBILE
	 * @mbggenerated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.MOBILE
	 * @param mobile  the value for user.MOBILE
	 * @mbggenerated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.ONLINE
	 * @return  the value of user.ONLINE
	 * @mbggenerated
	 */
	public Boolean getOnline() {
		return online;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.ONLINE
	 * @param online  the value for user.ONLINE
	 * @mbggenerated
	 */
	public void setOnline(Boolean online) {
		this.online = online;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.EMAIL
	 * @return  the value of user.EMAIL
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.EMAIL
	 * @param email  the value for user.EMAIL
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.MARK
	 * @return  the value of user.MARK
	 * @mbggenerated
	 */
	public Integer getMark() {
		return mark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.MARK
	 * @param mark  the value for user.MARK
	 * @mbggenerated
	 */
	public void setMark(Integer mark) {
		this.mark = mark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.MONEY
	 * @return  the value of user.MONEY
	 * @mbggenerated
	 */
	public Integer getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.MONEY
	 * @param money  the value for user.MONEY
	 * @mbggenerated
	 */
	public void setMoney(Integer money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.LOGIN_TIME
	 * @return  the value of user.LOGIN_TIME
	 * @mbggenerated
	 */
	public Date getLoginTime() {
		return loginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.LOGIN_TIME
	 * @param loginTime  the value for user.LOGIN_TIME
	 * @mbggenerated
	 */
	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.REG_TIME
	 * @return  the value of user.REG_TIME
	 * @mbggenerated
	 */
	public Date getRegTime() {
		return regTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.REG_TIME
	 * @param regTime  the value for user.REG_TIME
	 * @mbggenerated
	 */
	public void setRegTime(Date regTime) {
		this.regTime = regTime;
	}
}