/* Generated By:JavaCC: Do not edit this line. UbbParserConstants.java */
package com.pjxy.wap.util.ubb;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface UbbParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SIMPLE_TEXT = 1;
  /** RegularExpression Id. */
  int RIGHT_BRACKET = 2;
  /** RegularExpression Id. */
  int I_BEGIN = 3;
  /** RegularExpression Id. */
  int I_END = 4;
  /** RegularExpression Id. */
  int B_BEGIN = 5;
  /** RegularExpression Id. */
  int B_END = 6;
  /** RegularExpression Id. */
  int U_BEGIN = 7;
  /** RegularExpression Id. */
  int U_END = 8;
  /** RegularExpression Id. */
  int IMG_BEGIN = 9;
  /** RegularExpression Id. */
  int IMG_END = 10;
  /** RegularExpression Id. */
  int CALL_BEGIN = 11;
  /** RegularExpression Id. */
  int CALL_END = 12;
  /** RegularExpression Id. */
  int URL_BEGIN = 13;
  /** RegularExpression Id. */
  int URL_END = 14;
  /** RegularExpression Id. */
  int ON_BEGIN = 15;
  /** RegularExpression Id. */
  int ON_END = 16;
  /** RegularExpression Id. */
  int BR = 17;
  /** RegularExpression Id. */
  int TIME = 18;
  /** RegularExpression Id. */
  int DATE = 19;
  /** RegularExpression Id. */
  int WEEK = 20;
  /** RegularExpression Id. */
  int IP = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SIMPLE_TEXT>",
    "\")\"",
    "\"(i/)\"",
    "\"(/i)\"",
    "\"(b/)\"",
    "\"(/b)\"",
    "\"(u/)\"",
    "\"(/u)\"",
    "\"(img/)\"",
    "\"(/img)\"",
    "\"(call/)\"",
    "\"(/call)\"",
    "\"(url=\"",
    "\"(/url)\"",
    "\"(on/)\"",
    "\"(/on)\"",
    "<BR>",
    "\"(time/)\"",
    "\"(date/)\"",
    "\"(week/)\"",
    "\"(ip/)\"",
  };

}
