package com.pjxy.common.dao;

import com.pjxy.common.model.Admin;
import com.pjxy.common.model.AdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface AdminMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbggenerated
	 */
	@SelectProvider(type = AdminSqlProvider.class, method = "countByExample")
	int countByExample(AdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbggenerated
	 */
	@DeleteProvider(type = AdminSqlProvider.class, method = "deleteByExample")
	int deleteByExample(AdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbggenerated
	 */
	@Delete({ "delete from admin", "where ID = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbggenerated
	 */
	@Insert({
			"insert into admin (USER_ID, BLOCK_ID, ",
			"MANAGE_TYPE, CREATE_TIME, ",
			"USER_NAME)",
			"values (#{userId,jdbcType=INTEGER}, #{blockId,jdbcType=INTEGER}, ",
			"#{manageType,jdbcType=TINYINT}, #{createTime,jdbcType=TIMESTAMP}, ",
			"#{userName,jdbcType=VARCHAR})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
	int insert(Admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbggenerated
	 */
	@InsertProvider(type = AdminSqlProvider.class, method = "insertSelective")
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
	int insertSelective(Admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbggenerated
	 */
	@SelectProvider(type = AdminSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "ID", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "USER_ID", property = "userId", jdbcType = JdbcType.INTEGER),
			@Result(column = "BLOCK_ID", property = "blockId", jdbcType = JdbcType.INTEGER),
			@Result(column = "MANAGE_TYPE", property = "manageType", jdbcType = JdbcType.TINYINT),
			@Result(column = "CREATE_TIME", property = "createTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USER_NAME", property = "userName", jdbcType = JdbcType.VARCHAR) })
	List<Admin> selectByExample(AdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbggenerated
	 */
	@Select({ "select",
			"ID, USER_ID, BLOCK_ID, MANAGE_TYPE, CREATE_TIME, USER_NAME",
			"from admin", "where ID = #{id,jdbcType=INTEGER}" })
	@Results({
			@Result(column = "ID", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "USER_ID", property = "userId", jdbcType = JdbcType.INTEGER),
			@Result(column = "BLOCK_ID", property = "blockId", jdbcType = JdbcType.INTEGER),
			@Result(column = "MANAGE_TYPE", property = "manageType", jdbcType = JdbcType.TINYINT),
			@Result(column = "CREATE_TIME", property = "createTime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "USER_NAME", property = "userName", jdbcType = JdbcType.VARCHAR) })
	Admin selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbggenerated
	 */
	@UpdateProvider(type = AdminSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Admin record,
			@Param("example") AdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbggenerated
	 */
	@UpdateProvider(type = AdminSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Admin record,
			@Param("example") AdminExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbggenerated
	 */
	@UpdateProvider(type = AdminSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbggenerated
	 */
	@Update({ "update admin", "set USER_ID = #{userId,jdbcType=INTEGER},",
			"BLOCK_ID = #{blockId,jdbcType=INTEGER},",
			"MANAGE_TYPE = #{manageType,jdbcType=TINYINT},",
			"CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
			"USER_NAME = #{userName,jdbcType=VARCHAR}",
			"where ID = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Admin record);
}