package com.pjxy.common.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.pjxy.common.model.Block;
import com.pjxy.common.model.BlockExample.Criteria;
import com.pjxy.common.model.BlockExample.Criterion;
import com.pjxy.common.model.BlockExample;
import java.util.List;
import java.util.Map;

public class BlockSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table block
	 * @mbggenerated
	 */
	public String countByExample(BlockExample example) {
		BEGIN();
		SELECT("count (*)");
		FROM("block");
		applyWhere(example, false);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table block
	 * @mbggenerated
	 */
	public String deleteByExample(BlockExample example) {
		BEGIN();
		DELETE_FROM("block");
		applyWhere(example, false);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table block
	 * @mbggenerated
	 */
	public String insertSelective(Block record) {
		BEGIN();
		INSERT_INTO("block");
		if (record.getParent() != null) {
			VALUES("PARENT", "#{parent,jdbcType=INTEGER}");
		}
		if (record.getName() != null) {
			VALUES("`NAME`", "#{name,jdbcType=VARCHAR}");
		}
		if (record.getBanner() != null) {
			VALUES("BANNER", "#{banner,jdbcType=VARCHAR}");
		}
		if (record.getPostCount() != null) {
			VALUES("POST_COUNT", "#{postCount,jdbcType=INTEGER}");
		}
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table block
	 * @mbggenerated
	 */
	public String selectByExample(BlockExample example) {
		BEGIN();
		if (example != null && example.isDistinct()) {
			SELECT_DISTINCT("ID");
		} else {
			SELECT("ID");
		}
		SELECT("PARENT");
		SELECT("`NAME`");
		SELECT("BANNER");
		SELECT("POST_COUNT");
		FROM("block");
		applyWhere(example, false);
		if (example != null && example.getOrderByClause() != null) {
			ORDER_BY(example.getOrderByClause());
		}
		if (example.getLimitStart() >= 0)
			return SQL() + " limit " + example.getLimitStart() + ","
					+ example.getLimitEnd();
		else
			return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table block
	 * @mbggenerated
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		Block record = (Block) parameter.get("record");
		BlockExample example = (BlockExample) parameter.get("example");
		BEGIN();
		UPDATE("block");
		if (record.getId() != null) {
			SET("ID = #{record.id,jdbcType=INTEGER}");
		}
		if (record.getParent() != null) {
			SET("PARENT = #{record.parent,jdbcType=INTEGER}");
		}
		if (record.getName() != null) {
			SET("`NAME` = #{record.name,jdbcType=VARCHAR}");
		}
		if (record.getBanner() != null) {
			SET("BANNER = #{record.banner,jdbcType=VARCHAR}");
		}
		if (record.getPostCount() != null) {
			SET("POST_COUNT = #{record.postCount,jdbcType=INTEGER}");
		}
		applyWhere(example, true);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table block
	 * @mbggenerated
	 */
	public String updateByExample(Map<String, Object> parameter) {
		BEGIN();
		UPDATE("block");
		SET("ID = #{record.id,jdbcType=INTEGER}");
		SET("PARENT = #{record.parent,jdbcType=INTEGER}");
		SET("`NAME` = #{record.name,jdbcType=VARCHAR}");
		SET("BANNER = #{record.banner,jdbcType=VARCHAR}");
		SET("POST_COUNT = #{record.postCount,jdbcType=INTEGER}");
		BlockExample example = (BlockExample) parameter.get("example");
		applyWhere(example, true);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table block
	 * @mbggenerated
	 */
	public String updateByPrimaryKeySelective(Block record) {
		BEGIN();
		UPDATE("block");
		if (record.getParent() != null) {
			SET("PARENT = #{parent,jdbcType=INTEGER}");
		}
		if (record.getName() != null) {
			SET("`NAME` = #{name,jdbcType=VARCHAR}");
		}
		if (record.getBanner() != null) {
			SET("BANNER = #{banner,jdbcType=VARCHAR}");
		}
		if (record.getPostCount() != null) {
			SET("POST_COUNT = #{postCount,jdbcType=INTEGER}");
		}
		WHERE("ID = #{id,jdbcType=INTEGER}");
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table block
	 * @mbggenerated
	 */
	protected void applyWhere(BlockExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1,
									criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th,
									criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2,
									criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th,
									criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j,
										k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			WHERE(sb.toString());
		}
	}
}