package com.pjxy.common.dao;

import com.pjxy.common.model.Regist;
import com.pjxy.common.model.RegistExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface RegistMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regist
	 * @mbggenerated
	 */
	@SelectProvider(type = RegistSqlProvider.class, method = "countByExample")
	int countByExample(RegistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regist
	 * @mbggenerated
	 */
	@DeleteProvider(type = RegistSqlProvider.class, method = "deleteByExample")
	int deleteByExample(RegistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regist
	 * @mbggenerated
	 */
	@Delete({ "delete from regist", "where ID = #{id,jdbcType=INTEGER}" })
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regist
	 * @mbggenerated
	 */
	@Insert({ "insert into regist (MOBILE, CREATE_TIME)",
			"values (#{mobile,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
	int insert(Regist record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regist
	 * @mbggenerated
	 */
	@InsertProvider(type = RegistSqlProvider.class, method = "insertSelective")
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
	int insertSelective(Regist record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regist
	 * @mbggenerated
	 */
	@SelectProvider(type = RegistSqlProvider.class, method = "selectByExample")
	@Results({
			@Result(column = "ID", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "MOBILE", property = "mobile", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CREATE_TIME", property = "createTime", jdbcType = JdbcType.TIMESTAMP) })
	List<Regist> selectByExample(RegistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regist
	 * @mbggenerated
	 */
	@Select({ "select", "ID, MOBILE, CREATE_TIME", "from regist",
			"where ID = #{id,jdbcType=INTEGER}" })
	@Results({
			@Result(column = "ID", property = "id", jdbcType = JdbcType.INTEGER, id = true),
			@Result(column = "MOBILE", property = "mobile", jdbcType = JdbcType.VARCHAR),
			@Result(column = "CREATE_TIME", property = "createTime", jdbcType = JdbcType.TIMESTAMP) })
	Regist selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regist
	 * @mbggenerated
	 */
	@UpdateProvider(type = RegistSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Regist record,
			@Param("example") RegistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regist
	 * @mbggenerated
	 */
	@UpdateProvider(type = RegistSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Regist record,
			@Param("example") RegistExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regist
	 * @mbggenerated
	 */
	@UpdateProvider(type = RegistSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Regist record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table regist
	 * @mbggenerated
	 */
	@Update({ "update regist", "set MOBILE = #{mobile,jdbcType=VARCHAR},",
			"CREATE_TIME = #{createTime,jdbcType=TIMESTAMP}",
			"where ID = #{id,jdbcType=INTEGER}" })
	int updateByPrimaryKey(Regist record);
}