package com.pjxy.common.dao;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.pjxy.common.model.Reply;
import com.pjxy.common.model.ReplyExample.Criteria;
import com.pjxy.common.model.ReplyExample.Criterion;
import com.pjxy.common.model.ReplyExample;
import java.util.List;
import java.util.Map;

public class ReplySqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbggenerated
	 */
	public String countByExample(ReplyExample example) {
		BEGIN();
		SELECT("count (*)");
		FROM("reply");
		applyWhere(example, false);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbggenerated
	 */
	public String deleteByExample(ReplyExample example) {
		BEGIN();
		DELETE_FROM("reply");
		applyWhere(example, false);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbggenerated
	 */
	public String insertSelective(Reply record) {
		BEGIN();
		INSERT_INTO("reply");
		if (record.getUserId() != null) {
			VALUES("USER_ID", "#{userId,jdbcType=INTEGER}");
		}
		if (record.getPostId() != null) {
			VALUES("POST_ID", "#{postId,jdbcType=INTEGER}");
		}
		if (record.getCreateTime() != null) {
			VALUES("CREATE_TIME", "#{createTime,jdbcType=TIMESTAMP}");
		}
		if (record.getTop() != null) {
			VALUES("`TOP`", "#{top,jdbcType=BIT}");
		}
		if (record.getMark() != null) {
			VALUES("MARK", "#{mark,jdbcType=INTEGER}");
		}
		if (record.getUserName() != null) {
			VALUES("USER_NAME", "#{userName,jdbcType=VARCHAR}");
		}
		if (record.getContent() != null) {
			VALUES("CONTENT", "#{content,jdbcType=LONGVARCHAR}");
		}
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbggenerated
	 */
	public String selectByExampleWithBLOBs(ReplyExample example) {
		BEGIN();
		if (example != null && example.isDistinct()) {
			SELECT_DISTINCT("ID");
		} else {
			SELECT("ID");
		}
		SELECT("USER_ID");
		SELECT("POST_ID");
		SELECT("CREATE_TIME");
		SELECT("`TOP`");
		SELECT("MARK");
		SELECT("USER_NAME");
		SELECT("CONTENT");
		FROM("reply");
		applyWhere(example, false);
		if (example != null && example.getOrderByClause() != null) {
			ORDER_BY(example.getOrderByClause());
		}
		if (example.getLimitStart() >= 0)
			return SQL() + " limit " + example.getLimitStart() + ","
					+ example.getLimitEnd();
		else
			return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbggenerated
	 */
	public String selectByExample(ReplyExample example) {
		BEGIN();
		if (example != null && example.isDistinct()) {
			SELECT_DISTINCT("ID");
		} else {
			SELECT("ID");
		}
		SELECT("USER_ID");
		SELECT("POST_ID");
		SELECT("CREATE_TIME");
		SELECT("`TOP`");
		SELECT("MARK");
		SELECT("USER_NAME");
		FROM("reply");
		applyWhere(example, false);
		if (example != null && example.getOrderByClause() != null) {
			ORDER_BY(example.getOrderByClause());
		}
		if (example.getLimitStart() >= 0)
			return SQL() + " limit " + example.getLimitStart() + ","
					+ example.getLimitEnd();
		else
			return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbggenerated
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		Reply record = (Reply) parameter.get("record");
		ReplyExample example = (ReplyExample) parameter.get("example");
		BEGIN();
		UPDATE("reply");
		if (record.getId() != null) {
			SET("ID = #{record.id,jdbcType=INTEGER}");
		}
		if (record.getUserId() != null) {
			SET("USER_ID = #{record.userId,jdbcType=INTEGER}");
		}
		if (record.getPostId() != null) {
			SET("POST_ID = #{record.postId,jdbcType=INTEGER}");
		}
		if (record.getCreateTime() != null) {
			SET("CREATE_TIME = #{record.createTime,jdbcType=TIMESTAMP}");
		}
		if (record.getTop() != null) {
			SET("`TOP` = #{record.top,jdbcType=BIT}");
		}
		if (record.getMark() != null) {
			SET("MARK = #{record.mark,jdbcType=INTEGER}");
		}
		if (record.getUserName() != null) {
			SET("USER_NAME = #{record.userName,jdbcType=VARCHAR}");
		}
		if (record.getContent() != null) {
			SET("CONTENT = #{record.content,jdbcType=LONGVARCHAR}");
		}
		applyWhere(example, true);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbggenerated
	 */
	public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
		BEGIN();
		UPDATE("reply");
		SET("ID = #{record.id,jdbcType=INTEGER}");
		SET("USER_ID = #{record.userId,jdbcType=INTEGER}");
		SET("POST_ID = #{record.postId,jdbcType=INTEGER}");
		SET("CREATE_TIME = #{record.createTime,jdbcType=TIMESTAMP}");
		SET("`TOP` = #{record.top,jdbcType=BIT}");
		SET("MARK = #{record.mark,jdbcType=INTEGER}");
		SET("USER_NAME = #{record.userName,jdbcType=VARCHAR}");
		SET("CONTENT = #{record.content,jdbcType=LONGVARCHAR}");
		ReplyExample example = (ReplyExample) parameter.get("example");
		applyWhere(example, true);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbggenerated
	 */
	public String updateByExample(Map<String, Object> parameter) {
		BEGIN();
		UPDATE("reply");
		SET("ID = #{record.id,jdbcType=INTEGER}");
		SET("USER_ID = #{record.userId,jdbcType=INTEGER}");
		SET("POST_ID = #{record.postId,jdbcType=INTEGER}");
		SET("CREATE_TIME = #{record.createTime,jdbcType=TIMESTAMP}");
		SET("`TOP` = #{record.top,jdbcType=BIT}");
		SET("MARK = #{record.mark,jdbcType=INTEGER}");
		SET("USER_NAME = #{record.userName,jdbcType=VARCHAR}");
		ReplyExample example = (ReplyExample) parameter.get("example");
		applyWhere(example, true);
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbggenerated
	 */
	public String updateByPrimaryKeySelective(Reply record) {
		BEGIN();
		UPDATE("reply");
		if (record.getUserId() != null) {
			SET("USER_ID = #{userId,jdbcType=INTEGER}");
		}
		if (record.getPostId() != null) {
			SET("POST_ID = #{postId,jdbcType=INTEGER}");
		}
		if (record.getCreateTime() != null) {
			SET("CREATE_TIME = #{createTime,jdbcType=TIMESTAMP}");
		}
		if (record.getTop() != null) {
			SET("`TOP` = #{top,jdbcType=BIT}");
		}
		if (record.getMark() != null) {
			SET("MARK = #{mark,jdbcType=INTEGER}");
		}
		if (record.getUserName() != null) {
			SET("USER_NAME = #{userName,jdbcType=VARCHAR}");
		}
		if (record.getContent() != null) {
			SET("CONTENT = #{content,jdbcType=LONGVARCHAR}");
		}
		WHERE("ID = #{id,jdbcType=INTEGER}");
		return SQL();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbggenerated
	 */
	protected void applyWhere(ReplyExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1,
									criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th,
									criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2,
									criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th,
									criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j,
										k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			WHERE(sb.toString());
		}
	}
}